services:
  - type: web
    name: birthday-gift-server
    env: node
    rootDir: server
    buildCommand: npm install
    startCommand: node index.js
    envVars:
      - key: MONGODB_URI
        sync: false
      - key: CLIENT_URL
        sync: false
      - key: PORT
        value: 10000

  - type: web
    name: birthday-gift-client
    env: static
    rootDir: client
    buildCommand: npm install && npm run build
    staticPublishPath: ./dist
    routes:
      - type: rewrite
        source: /*
        destination: /index.html
    envVars:
      - key: VITE_API_URL
        sync: false
